repos:
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]
  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-docstrings
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
    - id: black
      language_version: python3.11
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        name: bandit (non-test code only)
        args: ['--exclude', 'tests/']
        exclude: '^app/utils/repl.py'
      - id: bandit
        name: bandit (test code only)
        args: ['-s', 'B101', 'tests/']
        exclude: '^app/utils/repl.py'
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.6.0
    hooks:
      - id: pycln
        args: [--all]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-ast
    - id: check-case-conflict
    - id: check-json
    - id: check-symlinks
    - id: check-toml
    - id: check-yaml
      exclude: '^k8s/'
    - id: check-added-large-files
      args: ['--maxkb=70']
    - id: detect-private-key
    - id: debug-statements
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace
    - id: requirements-txt-fixer
    - id: name-tests-test
      args: ['--pytest-test-first']
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify
