from typing import Literal

from pydantic import BaseModel, Field


class Keyword(BaseModel):
    keyword: str = Field(
        description="A descriptive phrase that captures one of the main concepts of the image. Not only present in the image description, but also represent the image."  # noqa: E501
    )
    flag: Literal["optional", "mandatory"] = Field(
        description="Whether the keyword is optional or mandatory."
    )
    priority: int = Field(
        description="A number that indicates the priority of the keyword. 1 is the highest priority and serially asign this (2,3,4,5,...)"  # noqa: E501
    )
    fallback_keywords: list[str] | None = Field(
        description="A list of general or related keywords that could be used if the main phrases are not found. If the keyword is mandatory, this field should be empty (None)."  # noqa: E501
    )


class FigureSearchCriteria(BaseModel):
    mandatory_keywords: list[Keyword] = Field(
        description="A list of mandatory keyword-phrases that must be represent the image."  # noqa: E501
    )
    optional_keywords: list[Keyword] = Field(
        description="A list of optional keyword-phrases that may be represent the image."  # noqa: E501
    )


class ImageSelection(BaseModel):
    image_number: str = Field(
        description="The unique identifier of the image (e.g., 'Figure 3b', '1')."
    )
    keyword_matches: list[str] = Field(
        description="A list of keywords phares that represent the image."
    )


class ImageSelectionOutput(BaseModel):
    selected_images: list[ImageSelection]


class ImageSuggested(BaseModel):
    image_number: str = Field(
        description="The unique identifier of the image (e.g., 'Figure 3b', '1')."
    )
    keyword_matches: list[str] = Field(
        description="A list of keywords phares that represent the image."
    )
    mandatory_keyword_match_count: int = Field(
        description="The number of mandatory keywords that match the image."
    )
    confidence_score: float = Field(
        description="The confidence score of the image suggestion."
    )


class AutoFigureConnectionAnnotation(BaseModel):
    id: int = Field(..., description="Unique identifier for the annotation")
    x: float = Field(..., description="X_TOP coordinate of the bounding box")
    y: float = Field(..., description="Y_TOP coordinate of the bounding box")
    width: float = Field(..., description="Width of the bounding box")
    height: float = Field(..., description="Height of the bounding box")
    pageNo: int = Field(..., description="Page number where the annotation is located")
    imgSrc: str = Field(..., description="URL of the image source for the annotation")
    type: Literal["plot", "table", "legend"] = Field(
        ..., description="Type of the annotation, can be 'plot', 'table', or 'legend'"
    )
    caption: str | None = Field(
        ...,
        description="Description of the figure/table given in the documents.",
    )
    description: str | None = Field(
        ..., description="Description of the figure generated by the AI."
    )
    footnote: str | None = Field(
        ...,
        description="Footnote given in the documents.",
    )


class AutoFigureSuggestion(BaseModel):
    id: int = Field(..., description="The id of the suggestion from AI database")
    type: str = Field(
        ..., description="The type of the suggestion from fullstack input type"
    )
    keyword: list[str] = Field(..., description="The keyword of the suggestion")
    confidence_score: float = Field(
        ...,
        description="The confidence score of the suggestion between 0 and 1",
        ge=0.0,
        le=1.0,
    )
    input_id: str = Field(..., description="The id of the input")


class AutoFigureSuggestionOutput(BaseModel):
    table_id: str = Field(..., description="The id of the table")
    file_id: str = Field(..., description="The id of the file")
    project_id: str = Field(..., description="The id of the project")
    suggestions: list[AutoFigureSuggestion] = Field(
        ..., description="The suggestions for the figures"
    )


class AutoFigureSuggestionPayload(BaseModel):
    table_id: str = Field(..., description="The id of the table")
    file_id: str = Field(..., description="The id of the file")
    flag_id: str = Field(..., description="The id of the flag")
    table_structure: dict = Field(..., description="The structure of the table")
    project_id: str = Field(..., description="The id of the project")


class AutoFigureSuggestionRequest(BaseModel):
    payload: AutoFigureSuggestionPayload = Field(
        ..., description="The payload of the request"
    )
    metadata: dict = Field(..., description="The metadata of the request")
