from typing import Literal

from pydantic import BaseModel, Field, HttpUrl


class AISuggested(BaseModel):
    status: bool = Field(
        ..., description="Flag to check whether it is suggested by AI or not"
    )
    description: list[str] = Field(
        ..., description="Matched keywords if suggested by AI"
    )


class AutoFigureConnectionAnnotation(BaseModel):
    id: int = Field(..., description="Unique identifier for the annotation")
    x: float = Field(..., description="X_TOP coordinate of the bounding box")
    y: float = Field(..., description="Y_TOP coordinate of the bounding box")
    width: float = Field(..., description="Width of the bounding box")
    height: float = Field(..., description="Height of the bounding box")
    pageNo: int = Field(..., description="Page number where the annotation is located")
    imgSrc: HttpUrl = Field(
        ..., description="URL of the image source for the annotation"
    )
    type: Literal["plot", "table", "legend"] = Field(
        ..., description="Type of the annotation, can be 'plot', 'table', or 'legend'"
    )
    caption: str | None = Field(
        ...,
        description="Description of the figure/table given in the documents.",
    )
    description: str | None = Field(
        ..., description="Description of the figure generated by the AI."
    )
    footnote: str | None = Field(
        ...,
        description="Footnote given in the documents.",
    )
    aiSuggested: AISuggested | None = Field(
        ..., description="Data to check whether it is suggested by AI or not"
    )


class AutoFigureConnection(BaseModel):
    isAiProcessDone: bool = Field(
        ..., description="Indicates if the mineru process is done"
    )
    annotations: list[AutoFigureConnectionAnnotation]
