"""file details

Revision ID: 19b9b7b3bd7b
Revises: 6977130f538f
Create Date: 2025-03-13 15:21:02.028995

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "19b9b7b3bd7b"
down_revision: str | None = "6977130f538f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_details",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("flag_id", sa.Uuid(), nullable=False),
        sa.Column("supplementary_id", sa.Text(), nullable=True),
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("file_extension", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("doi", sa.Text(), nullable=True),
        sa.Column("doi_url", sa.Text(), nullable=True),
        sa.Column("publication_type", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("authors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("funder", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("publisher", sa.Text(), nullable=True),
        sa.Column(
            "published_date", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("issue", sa.Text(), nullable=True),
        sa.Column("issue_date", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("volume", sa.Text(), nullable=True),
        sa.Column("page", sa.Text(), nullable=True),
        sa.Column("license", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("container_title", sa.Text(), nullable=True),
        sa.Column("ISSN", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reference_count", sa.Integer(), nullable=True),
        sa.Column("references", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("referenced_by_count", sa.Integer(), nullable=True),
        sa.Column(
            "raw_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("file_details")
    # ### end Alembic commands ###
