"""MinerU output logs

Revision ID: 6977130f538f
Revises: cbb7a0a228a0
Create Date: 2025-01-21 15:58:14.198106

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6977130f538f"
down_revision: str | None = "cbb7a0a228a0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mineru_responses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("flag_id", sa.Uuid(), nullable=False),
        sa.Column(
            "response_type",
            sa.Enum("initial", "final", name="response_type_enum"),
            nullable=False,
        ),
        sa.Column("response", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mineru_responses")
    # ### end Alembic commands ###
