"""table information

Revision ID: 6f36edf471a1
Revises: cec6c1eb6e8d
Create Date: 2024-12-30 16:50:19.242531

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.database.models import JsonList

# revision identifiers, used by Alembic.
revision: str = "6f36edf471a1"
down_revision: str | None = "cec6c1eb6e8d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "table_details",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("flag_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("table_id", sa.Uuid(), nullable=False),
        sa.Column("table_number", sa.Text(), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("digitized", sa.Text(), nullable=False),
        sa.Column("footnote", sa.Text(), nullable=True),
        sa.Column("normalized_bbox_coordinates", JsonList(), nullable=False),
        sa.Column("converted_bbox_coordinates", JsonList(), nullable=False),
        sa.Column("bucket_path", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("table_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("table_details")
    # ### end Alembic commands ###
