"""mineru_response_supp_id

Revision ID: a5e643d25be5
Revises: 19b9b7b3bd7b
Create Date: 2025-03-17 21:34:07.788335

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5e643d25be5"
down_revision: str | None = "19b9b7b3bd7b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mineru_responses", sa.Column("supplementary_id", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mineru_responses", "supplementary_id")
    # ### end Alembic commands ###
