"""legend bounding box mapping schema added

Revision ID: adc16f65ca7c
Revises: ca063f617fe1
Create Date: 2025-07-11 12:17:01.842263

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.database.models import JsonList

# revision identifiers, used by Alembic.
revision: str = "adc16f65ca7c"
down_revision: str | None = "ca063f617fe1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "figure_details",
        sa.Column("legend_converted_bbox_coordinates", JsonList(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("figure_details", "legend_converted_bbox_coordinates")
