"""add

Revision ID: ca063f617fe1
Revises: fb3942f8d853
Create Date: 2025-06-19 12:42:25.116518

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca063f617fe1"
down_revision: str | None = "fb3942f8d853"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file_details", sa.Column("paper_summary", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file_details", "paper_summary")
    # ### end Alembic commands ###
