"""multiple legend paths

Revision ID: cbb7a0a228a0
Revises: 6f36edf471a1
Create Date: 2024-12-30 18:05:50.955722

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.database.models import JsonList

# revision identifiers, used by Alembic.
revision: str = "cbb7a0a228a0"
down_revision: str | None = "6f36edf471a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "figure_details",
        sa.Column("legend_paths", JsonList(), nullable=True),
    )
    op.drop_column("figure_details", "legend_path")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "figure_details",
        sa.Column("legend_path", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column("figure_details", "legend_paths")
    # ### end Alembic commands ###
