"""figure and page information

Revision ID: cec6c1eb6e8d
Revises:
Create Date: 2024-12-27 18:31:49.885333

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.database.models import JsonList

# revision identifiers, used by Alembic.
revision: str = "cec6c1eb6e8d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "figure_details",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("flag_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("figure_id", sa.Uuid(), nullable=False),
        sa.Column("parent_figure_id", sa.Uuid(), nullable=True),
        sa.Column("figure_number", sa.Text(), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("footnote", sa.Text(), nullable=True),
        sa.Column("normalized_bbox_coordinates", JsonList(), nullable=False),
        sa.Column("converted_bbox_coordinates", JsonList(), nullable=False),
        sa.Column("bucket_path", sa.Text(), nullable=False),
        sa.Column("legend_path", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("figure_id"),
    )
    op.create_table(
        "page_details",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("flag_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("bucket_path", sa.Text(), nullable=False),
        sa.Column("image_width", sa.Integer(), nullable=False),
        sa.Column("image_height", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("page_details")
    op.drop_table("figure_details")
    # ### end Alembic commands ###
