"""add supplementary column to figure_details

Revision ID: fb3942f8d853
Revises: a5e643d25be5
Create Date: 2025-05-27 18:58:01.135084

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb3942f8d853"
down_revision: str | None = "a5e643d25be5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "figure_details", sa.Column("supplementary_id", sa.Text(), nullable=True)
    )
    op.add_column(
        "page_details", sa.Column("supplementary_id", sa.Text(), nullable=True)
    )
    op.add_column(
        "table_details", sa.Column("supplementary_id", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("table_details", "supplementary_id")
    op.drop_column("page_details", "supplementary_id")
    op.drop_column("figure_details", "supplementary_id")
    # ### end Alembic commands ###
