from enum import Enum

from dotenv import load_dotenv

load_dotenv()


class TableNames(Enum):
    OBSERVATION = "plot"
    COVARIATE = "covariate"
    DOSING = "dosing"


OBSERVATION_COLUMNS_TO_DROP = [
    "fileId",
    "paperTitle",
    "paperStatus",
    "figure",
    "lineStatus",
    "ARM_ID_UNIT",
    "N_STUDY_UNIT",
    "N_ARM_UNIT",
    "DVID_UNIT",
    "DV_VAR_UNIT",
    "N_RANDOMIZED_UNIT",
    "N_EVALUABLE_UNIT",
    "N_DROPOUTS_UNIT",
    "images",
    "projectId",
    "flagId",
]

COVARIATE_COLUMNS_TO_DROP = [
    "fileId",
    "paperTitle",
    "paperStatus",
    "figure",
    "lineStatus",
    "images",
    "projectId",
    "flagId",
]

DOSING_COLUMNS_TO_DROP = [
    "fileId",
    "paperTitle",
    "paperStatus",
    "figure",
    "lineStatus",
    "images",
    "projectId",
    "flagId",
]

# Combined list of all columns to drop at the end of the merge pipeline
# This ensures columns are removed regardless of which table they came from
FINAL_COLUMNS_TO_DROP = [
    "fileId",
    "paperTitle",
    "paperStatus",
    "figure",
    "lineStatus",
    "images",
    "projectId",
    "flagId",
]

# ----- New (non-legacy) merge flow constants -----
# Map from possible column names (after uppercase) to final schema name.
RENAME_MAP: dict[str, str] = {
    "FILENAME": "FILE_NAME",
    "STU_NUMBER": "STU_NUMBER",
    "TRIAL_NAME": "TRIAL_NAME",
    "GROUP": "GROUP_NAME",
    "GROUP_NAME": "GROUP_NAME",
    "AU": "AU",
    "TI": "TITLE",
    "JR": "JOURNAL_NAME",
    "PY": "YEAR",
    "TITLE": "TITLE",
    "JOURNAL_NAME": "JOURNAL_NAME",
    "YEAR": "YEAR",
    "VL": "VL",
    "IS": "IS",
    "PG": "PG",
    "LA": "LA",
    "REGID": "REGID",
    "REGNM": "REGNM",
    "TP": "TP",
    "TS": "TS",
    "DOI": "DOI_URL",
    "DOI_URL": "DOI_URL",
    "CIT_URL": "CIT_URL",
    "PUBMED_ID": "PUBMED_ID",
    "TRIAL_ID": "TRIAL_ID",
    "COUNTRY": "COUNTRY",
    "SPONSOR_TYPE": "SPONSOR_TYPE",
    "BLINDING": "BLINDING",
    "BLINIDING": "BLINDING",
    "NEW_ONSET_T1DM": "NEW_ONSET_T1DM",
    "SOC_DESCRIPTION": "SOC_DESCRIPTION",
    "STUDY_DESIGN": "STUDY_DESIGN",
    "NOTES": "NOTES",
    "ENDPOINT_DURATION_MONTHS": "ENDPOINT_DURATION_MONTHS",
    "STD_IND": "STD_IND",
    "STD_TRT": "STD_TRT",
    "STD_TRT_CLASS": "STD_TRT_CLASS",
    "SOURCE": "SOURCE",
    "NUMBER_OF_ARMS": "NUMBER_OF_ARMS",
    "ARM_NUMBER": "ARM_NUMBER",
    "ARM_TRT": "ARM_TRT",
    "ARM_TRT_CLASS": "ARM_TRT_CLASS",
    "ARM_DOSE": "ARM_DOSE",
    "ARM_DOSE_UNIT": "ARM_DOSE_UNIT",
    "AMT": "AMT",
    "AMT_UNIT": "AMT_UNIT",
    "REGIMEN": "REGIMEN",
    "N_STUDY": "N_STUDY",
    "N_ARM": "N_ARM",
    "ROUTE": "ROUTE",
    "ARM_TIME": "ARM_TIME",
    "ARM_TIME_UNIT": "ARM_TIME_UNIT",
    "DVID": "DVID",
    "ENDPOINT": "ENDPOINT",
    "DV_STAT": "DV_STAT",
    "DV": "DV",
    "DV_UNIT": "DV_UNIT",
    "DV_VAR_STAT": "DV_VAR_STAT",
    "DV_VAR_UPPER": "DV_VAR_UPPER",
    "DV_VAR_LOWER": "DV_VAR_LOWER",
    "DV_VAR": "DV_VAR",
    "LLOQ": "LLOQ",
    "EVID": "EVID",
    "MDV": "MDV",
    "ADDL": "ADDL",
    "II": "II",
    "II_UNIT": "II_UNIT",
    "ARM_DUR": "ARM_DUR",
    "ARM_DUR_UNIT": "ARM_DUR_UNIT",
    "AGE_BL": "AGE_BL",
    "AGE_BL_UNIT": "AGE_BL_UNIT",
    "AGE_BL_VAR": "AGE_BL_VAR",
    "AGE_BL_VAR_STAT": "AGE_BL_VAR_STAT",
    "AGE_BL_STAT": "AGE_BL_STAT",
    "MALE_PERCENT_BL": "MALE_PERCENT_BL",
    "FEMALE_PERCENT_BL": "FEMALE_PERCENT_BL",
    "BMI_BL": "BMI_BL",
    "BMI_BL_UNIT": "BMI_BL_UNIT",
    "BMI_BL_STAT": "BMI_BL_STAT",
    "BMI_BL_VAR": "BMI_BL_VAR",
    "BMI_BL_VAR_STAT": "BMI_BL_VAR_STAT",
    "BW_BL": "BW_BL",
    "BW_BL_UNIT": "BW_BL_UNIT",
    "BW_BL_STAT": "BW_BL_STAT",
    "BW_BL_VAR": "BW_BL_VAR",
    "BW_BL_VAR_STAT": "BW_BL_VAR_STAT",
    "HT_BL": "HT_BL",
    "HT_BL_UNIT": "HT_BL_UNIT",
    "HT_BL_STAT": "HT_BL_STAT",
    "HT_BL_VAR": "HT_BL_VAR",
    "HT_BL_VAR_STAT": "HT_BL_VAR_STAT",
    "ETHN_HISPANIC_PERC": "ETHN_HISPANIC_PERC",
    "ETHN_NONHISPANIC_PERC": "ETHN_NONHISPANIC_PERC",
    "RACE_ASIAN_PERC": "RACE_ASIAN_PERC",
    "RACE_WHITE_PERC": "RACE_WHITE_PERC",
    "RACE_BLACK_AA_PERC": "RACE_BLACK_AA_PERC",
    "RACE_OTHER_PERC": "RACE_OTHER_PERC",
    "RACE_NON_REPORT_PERC": "RACE_NON_REPORT_PERC",
    "TCI": "TCI",
    "TCS": "TCS",
    "TCI_OR_TCS_BL": "TCI_OR_TCS_BL",
    "TCI_AND_TCS_BL": "TCI_AND_TCS_BL",
    "AD_DUR_BL": "AD_DUR_BL",
    "AD_DUR_BL_UNIT": "AD_DUR_BL_UNIT",
    "AD_DUR_STAT": "AD_DUR_STAT",
    "AD_DUR_VAR": "AD_DUR_VAR",
    "AD_DUR_VAR_STAT": "AD_DUR_VAR_STAT",
    "AGE_OF_ONSET_SUB18": "AGE_OF_ONSET_SUB18",
    "AGE_OF_ONSET_SUPRA18": "AGE_OF_ONSET_SUPRA18",
    "EASI_BL": "EASI_BL",
    "EASI_BL_STAT": "EASI_BL_STAT",
    "EASI_BL_VAR": "EASI_VAR",
    "EASI_BL_VAR_STAT": "EASI_VAR_STAT",
    "PNRS_BL": "PNRS_BL",
    "PNRS_BL_STAT": "PNRS_BL_STAT",
    "PNRS_BL_VAR": "PNRS_VAR",
    "PNRS_BL_VAR_STAT": "PNRS_VAR_STAT",
    "SNRS_BL": "SNRS_BL",
    "SNRS_BL_STAT": "SNRS_BL_STAT",
    "SNRS_BL_VAR": "SNRS_VAR",
    "SNRS_BL_VAR_STAT": "SNRS_VAR_STAT",
    "IGA_BL": "IGA_BL",
    "IGA_BL_STAT": "IGA_BL_STAT",
    "IGA_BL_VAR": "IGA_VAR",
    "IGA_BL_VAR_STAT": "IGA_VAR_STAT",
    "AFF_BSA_BL": "AFF_BSA_BL",
    "AFF_BSA_BL_UNIT": "AFF_BSA_BL_UNIT",
    "AFF_BSA_BL_STAT": "AFF_BSA_BL_STAT",
    "AFF_BSA_BL_VAR": "AFF_BSA_VAR",
    "AFF_BSA_VAR_STAT": "AFF_BSA_VAR_STAT",
    "SCORAD_BL": "SCORAD_BL",
    "SCORAD_BL_STAT": "SCORAD_BL_STAT",
    "SCORAD_BL_VAR": "SCORAD_VAR",
    "SCORAD_BL_VAR_STAT": "SCORAD_VAR_STAT",
    "POEM_BL": "POEM_BL",
    "POEM_BL_STAT": "POEM_BL_STAT",
    "POEM_BL_VAR": "POEM_VAR",
    "POEM_BL_VAR_STAT": "POEM_VAR_STAT",
    "DLQI_BL": "DLQI_BL",
    "DLQI_BL_STAT": "DLQI_BL_STAT",
    "DLQI_BL_VAR": "DLQI_VAR",
    "DLQI_BL_VAR_STAT": "DLQI_VAR_STAT",
    "ALLERGIC_AD": "ALLERGIC_AD",
    "NONALLERGIC_AD": "NONALLERGIC_AD",
    "IGE_BL": "IGE_BL",
    "IGE_BL_UNIT": "IGE_BL_UNIT",
    "IGE_BL_STAT": "IGE_BL_STAT",
    "IGE_BL_VAR": "IGE_VAR",
    "IGE_BL_VAR_STAT": "IGE_VAR_STAT",
}

# Paper/study-level columns (from paper_labels); appear on every row after GROUP_NAME.
PAPER_LABELS_COLUMNS: list[str] = [
    "PUBMED_ID",
    "TRIAL_ID",
    "TITLE",
    "JOURNAL_NAME",
    "YEAR",
    "COUNTRY",
    "SPONSOR_TYPE",
    "BLINDING",
    "NEW_ONSET_T1DM",
    "ENDPOINT_DURATION_MONTHS",
    "SOC_DESCRIPTION",
    "STUDY_DESIGN",
    "NOTES",
]

# Final column order for new merge output. Paper labels columns come first.
FINAL_COLUMNS: list[str] = [
    "FILE_NAME",
    "STU_NUMBER",
    "TRIAL_NAME",
    "GROUP_NAME",
    "PUBMED_ID",
    "TRIAL_ID",
    "TITLE",
    "JOURNAL_NAME",
    "YEAR",
    "COUNTRY",
    "SPONSOR_TYPE",
    "BLINDING",
    "NEW_ONSET_T1DM",
    "ENDPOINT_DURATION_MONTHS",
    "SOC_DESCRIPTION",
    "STUDY_DESIGN",
    "NOTES",
    "AU",
    "VL",
    "IS",
    "PG",
    "LA",
    "REGID",
    "REGNM",
    "TP",
    "TS",
    "DOI_URL",
    "CIT_URL",
    "STD_IND",
    "STD_TRT",
    "STD_TRT_CLASS",
    "SOURCE",
    "NUMBER_OF_ARMS",
    "ARM_NUMBER",
    "ARM_TRT",
    "ARM_TRT_CLASS",
    "ARM_DOSE",
    "ARM_DOSE_UNIT",
    "AMT",
    "AMT_UNIT",
    "REGIMEN",
    "N_STUDY",
    "N_ARM",
    "ROUTE",
    "ARM_TIME",
    "ARM_TIME_UNIT",
    "DVID",
    "ENDPOINT",
    "DV_STAT",
    "DV",
    "DV_UNIT",
    "DV_VAR_STAT",
    "DV_VAR_UPPER",
    "DV_VAR_LOWER",
    "DV_VAR",
    "LLOQ",
    "EVID",
    "MDV",
    "ADDL",
    "II",
    "II_UNIT",
    "ARM_DUR",
    "ARM_DUR_UNIT",
    "AGE_BL",
    "AGE_BL_UNIT",
    "AGE_BL_VAR",
    "AGE_BL_VAR_STAT",
    "AGE_BL_STAT",
    "MALE_PERCENT_BL",
    "FEMALE_PERCENT_BL",
    "BMI_BL",
    "BMI_BL_UNIT",
    "BMI_BL_STAT",
    "BMI_BL_VAR",
    "BMI_BL_VAR_STAT",
    "BW_BL",
    "BW_BL_UNIT",
    "BW_BL_STAT",
    "BW_BL_VAR",
    "BW_BL_VAR_STAT",
    "HT_BL",
    "HT_BL_UNIT",
    "HT_BL_STAT",
    "HT_BL_VAR",
    "HT_BL_VAR_STAT",
    "ETHN_HISPANIC_PERC",
    "ETHN_NONHISPANIC_PERC",
    "RACE_ASIAN_PERC",
    "RACE_WHITE_PERC",
    "RACE_BLACK_AA_PERC",
    "RACE_OTHER_PERC",
    "RACE_NON_REPORT_PERC",
    "TCI",
    "TCS",
    "TCI_OR_TCS_BL",
    "TCI_AND_TCS_BL",
    "AD_DUR_BL",
    "AD_DUR_BL_UNIT",
    "AD_DUR_STAT",
    "AD_DUR_VAR",
    "AD_DUR_VAR_STAT",
    "AGE_OF_ONSET_SUB18",
    "AGE_OF_ONSET_SUPRA18",
    "EASI_BL",
    "EASI_BL_STAT",
    "EASI_VAR",
    "EASI_VAR_STAT",
    "PNRS_BL",
    "PNRS_BL_STAT",
    "PNRS_VAR",
    "PNRS_VAR_STAT",
    "SNRS_BL",
    "SNRS_BL_STAT",
    "SNRS_VAR",
    "SNRS_VAR_STAT",
    "IGA_BL",
    "IGA_BL_STAT",
    "IGA_VAR",
    "IGA_VAR_STAT",
    "AFF_BSA_BL",
    "AFF_BSA_BL_UNIT",
    "AFF_BSA_BL_STAT",
    "AFF_BSA_VAR",
    "AFF_BSA_VAR_STAT",
    "SCORAD_BL",
    "SCORAD_BL_STAT",
    "SCORAD_VAR",
    "SCORAD_VAR_STAT",
    "POEM_BL",
    "POEM_BL_STAT",
    "POEM_VAR",
    "POEM_VAR_STAT",
    "DLQI_BL",
    "DLQI_BL_STAT",
    "DLQI_VAR",
    "DLQI_VAR_STAT",
    "ALLERGIC_AD",
    "NONALLERGIC_AD",
    "IGE_BL",
    "IGE_BL_UNIT",
    "IGE_BL_STAT",
    "IGE_VAR",
    "IGE_VAR_STAT",
]

# Columns to back-fill by group (ffill/bfill) in new merge flow.
ARM_LEVEL_COLS: list[str] = [
    "file_name",
    "stu_number",
    "trial_name",
    "group_name",
    "au",
    "title",
    "journal_name",
    "year",
    "vl",
    "is",
    "pg",
    "la",
    "regid",
    "regnm",
    "tp",
    "ts",
    "doi_url",
    "cit_url",
    "std_ind",
    "std_trt",
    "std_trt_class",
    "number_of_arms",
    "arm_number",
    "arm_trt",
    "arm_trt_class",
    "arm_dose",
    "arm_dose_unit",
    "regimen",
    "n_study",
    "n_arm",
]

# Columns to fill from OBS into DOSE rows (by group).
FROM_OBS_COLS: list[str] = [
    "group_name",
    "number_of_arms",
    "arm_number",
    "arm_trt",
    "arm_trt_class",
    "arm_dose",
    "arm_dose_unit",
    "regimen",
    "n_study",
    "n_arm",
]

# After merge: propagate by GROUP (uppercase names).
POST_FILL_COLS: list[str] = [
    "FILE_NAME",
    "STU_NUMBER",
    "TRIAL_NAME",
    "GROUP_NAME",
    "AU",
    "TITLE",
    "JOURNAL_NAME",
    "YEAR",
    "VL",
    "IS",
    "PG",
    "LA",
    "REGID",
    "REGNM",
    "TP",
    "TS",
    "DOI_URL",
    "CIT_URL",
    "STD_IND",
    "STD_TRT",
    "STD_TRT_CLASS",
    "NUMBER_OF_ARMS",
    "ARM_NUMBER",
    "ARM_TRT",
    "ARM_TRT_CLASS",
    "ARM_DOSE",
    "ARM_DOSE_UNIT",
    "REGIMEN",
    "N_STUDY",
    "N_ARM",
]
