from dotenv import load_dotenv

load_dotenv()

MAX_RETRIES = 5
REPLACED_VALUE_KEY = "replaced_values_during_standardization"
FOUND_ERROR_KEY = "found_errors_during_standardization"


UNIT_MAPPINGS = {
    "unit/ml": "U/ml",
    "centimeter": "cm",
    "meter": "m",
    "kilometer": "km",
    "millimeter": "mm",
    "micrometer": "µm",
    "nanometer": "nm",
    "mmhg": "mmHg",
    "inch": "in",
    "foot": "ft",
    "yard": "yd",
    "mile": "mi",
    "gram": "g",
    "kilogram": "kg",
    "milligram": "mg",
    "microgram": "µg",
    "ton": "t",
    "ounce": "oz",
    "pound": "lb",
    "liter": "l",
    "milliliter": "ml",
    "cubic meter": "m³",
    "cubic centimeter": "cm³",
    "gallon": "gal",
    "quart": "qt",
    "pint": "pt",
    "cup": "c",
    "tablespoon": "tbsp",
    "teaspoon": "tsp",
    "ampere": "A",
    "milliampere": "mA",
    "volt": "V",
    "kilovolt": "kV",
    "watt": "W",
    "kilowatt": "kW",
    "megawatt": "MW",
    "joule": "J",
    "kilojoule": "kJ",
    "calorie": "cal",
    "kilocalorie": "kcal",
    "newton": "N",
    "pascal": "Pa",
    "hectopascal": "hPa",
    "kilopascal": "kPa",
    "bar": "bar",
    "atmosphere": "atm",
    "degree Celsius": "°C",
    "degree Fahrenheit": "°F",
    "kelvin": "K",
    "mole": "mol",
    "candela": "cd",
    "lumen": "lm",
    "lux": "lx",
    "becquerel": "Bq",
    "gray": "Gy",
    "sievert": "Sv",
    "hertz": "Hz",
    "kilohertz": "kHz",
    "megahertz": "MHz",
    "gigahertz": "GHz",
    "ohm": "Ω",
    "siemens": "S",
    "farad": "F",
    "henry": "H",
    "weber": "Wb",
    "tesla": "T",
    "coulomb": "C",
    "radian": "rad",
    "steradian": "sr",
    "picometer": "pm",
    "nautical mile": "nmi",
    "stone": "st",
    "cubic inch": "in³",
    "cubic foot": "ft³",
    "barrel": "bbl",
    "dyne": "dyn",
    "angstrom": "Å",
    "parsec": "pc",
    "light year": "ly",
    "electronvolt": "eV",
    "erg": "erg",
    "horsepower": "hp",
    "british thermal unit": "BTU",
    "h": "hours",
    "s": "seconds",
    "ms": "milliseconds",
    "µs": "microseconds",
    "ns": "nanoseconds",
    "d": "days",
    "wk": "weeks",
    "mo": "months",
    "yr": "years",
    "min": "minutes",
    "hr": "hours",
    "sec": "seconds",
    "hour": "hours",
    "second": "seconds",
    "minute": "minutes",
    "day": "days",
    "week": "weeks",
    "month": "months",
    "year": "years",
    "millisecond": "milliseconds",
    "microsecond": "microseconds",
    "nanosecond": "nanoseconds",
}

ROUTE_MAPPINGS = {
    "subcutaneous": "SC",
    "sc": "SC",
    "Oral": "oral",
    "intramuscular": "IM",
    "intravenous": "IV",
    "intravenous infusion": "IV",
    "intravenous infusion (drip)": "IV",
    "sublingual": "SL",
    "intrathecal": "IT",
    "intradermal": "ID",
    "intraosseous": "IO",
    "intraperitoneal": "IP",
    "intracardiac": "IC",
    "intra-arterial": "IA",
    "transdermal": "TD",
    "inhalation": "INH",
    "epidural": "EP",
    "intra-articular": "IA",
    "intranasal": "IN",
    "percutaneous": "PC",
}

STATISTICAL_ABBREVIATIONS = {
    "Mean": "mean",
    "Geometric Mean": "geometric mean",
    "gm": "geometric mean",
    "mean cfb": "mean CFB",
    "standard deviation": "SD",
    "standard error": "SE",
    "standard error from the mean": "SEM",
    "inter quartile range": "IQR",
    "Range": "range",
    "confidence interval": "95% CI",
    "95% confidence interval": "95% CI",
    "95%ci": "95% CI",
    "90% confidence interval": "90% CI",
    "90%ci": "90% CI",
    "coefficient of variation": "CV",
    "sample size": "N",
    "p-value": "p",
    "correlation coefficient": "r",
    "regression coefficient": "β",
    "odds ratio": "OR",
    "relative risk": "RR",
    "chi-square": "χ²",
    "degrees of freedom": "df",
    "t-statistic": "t",
    "z-score": "z",
    "f-statistic": "F",
    "anova": "ANOVA",
    "multivariate analysis of variance": "MANOVA",
    "analysis of covariance": "ANCOVA",
    "principal component analysis": "PCA",
    "factor analysis": "FA",
    "likelihood ratio": "LR",
    "bayesian information criterion": "BIC",
    "akaike information criterion": "AIC",
    "change from baseline": "CFB",
    "least square mean": "LS mean",
    "least square means": "LS mean",
    "least squares mean": "LS mean",
    "least squares means": "LS mean",
    "mean change from baseline": "mean CFB",
    "ls mean": "LS mean",
    "ls_mean": "LS mean",
    "LS Mean": "LS mean",
    "LS Mean CFB": "LS mean CFB",
    "least square means;cfb": "LS mean CFB",
    "least square mean;cfb": "LS mean CFB",
    "least squares means;cfb": "LS mean CFB",
    "least squares mean;cfb": "LS mean CFB",
    "area under the curve": "AUC",
    "confidence level": "CL",
    "mean absolute deviation": "MAD",
    "mean squared error": "MSE",
    "root mean square error": "RMSE",
    "sum of squares": "SS",
    "total sum of squares": "TSS",
    "residual sum of squares": "RSS",
    "explained sum of squares": "ESS",
    "adjusted r-squared": "Adj R²",
    "cumulative distribution function": "CDF",
    "probability density function": "PDF",
    "maximum likelihood estimation": "MLE",
    "generalized linear model": "GLM",
    "log-likelihood": "LL",
    "receiver operating characteristic": "ROC",
    "area under the ROC curve": "AUC-ROC",
    "false discovery rate": "FDR",
    "false positive rate": "FPR",
    "true positive rate": "TPR",
    "negative predictive value": "NPV",
    "positive predictive value": "PPV",
    "bayes factor": "BF",
    "cumulative incidence": "CI",
    "hazard ratio": "HR",
    "kurtosis": "K",
    "skewness": "Sk",
    "mean absolute percentage error": "MAPE",
    "Percentage": "percentage",
    "median absolute deviation": "MAD",
    "Median": "median",
    "mean bias error": "MBE",
    "mean squared prediction error": "MSPE",
    "partial correlation coefficient": "PCC",
    "proportion of variance explained": "PVE",
    "quantile regression": "QR",
    "relative standard error": "RSE",
    "standardized mean difference": "SMD",
    "time to event": "TTE",
    "variance inflation factor": "VIF",
    "weighted least squares": "WLS",
    "zero-inflated model": "ZIM",
}

REGIMEN_ABBREVIATIONS = {
    "single dose/dosage": "single dose",
    "alt. hor.": "alternate hours",
    "alt. noct.": "alternate nights",
    "qod": "every other day",
    "qp": "as much as desired",
    "qs": "a sufficient quantity",
    "qhs": "at bedtime",
    "on": "every night",
    "om": "every morning",
    "oh": "every hour",
    "q2h": "once every 2 hours",
    "qnh": "once every n hours",
    "bih": "twice hourly",
    "tih": "three times hourly",
    "qih": "four times hourly",
    "qd": "every day, once daily",
    "q2d": "every 2 days",
    "qnd": "every n days",
    "bid": "twice daily, Q-12h hourly",
    "tid": "thrice daily, Q-8th hourly",
    "qid": "four times a day, Q-6th hourly",
    "qw": "once weekly",
    "q2w": "every 2 weeks",
    "qnw": "once every n weeks",
    "biw": "twice weekly",
    "tiw": "three times weekly",
    "qiw": "four times weekly",
    "qm": "every month",
    "q2m": "every 2 months",
    "qnm": "once every n months",
    "tim": "three times monthly",
    "qim": "four times monthly",
}


SIMILAR_REGIMEN_MAPPING = {
    "ad. lib.": "qp",
    "dieb. alt.": "qod",
    "alt. dieb.": "qod",
    "qad": "qod",
    "prn": "qp",
    "qv": "qp",
    "bd": "bid",
    "single": "single dose",
    "single dosage": "single dose",
}

# COLUMNS_TO_CHECK = ["T2D_DUR_BL_VAR_STAT"]
SUPERSCRIPT_MAP = {
    "⁰": "0",
    "¹": "1",
    "²": "2",
    "³": "3",
    "⁴": "4",
    "⁵": "5",
    "⁶": "6",
    "⁷": "7",
    "⁸": "8",
    "⁹": "9",
}
SUBSCRIPT_MAP = {
    "₀": "0",
    "₁": "1",
    "₂": "2",
    "₃": "3",
    "₄": "4",
    "₅": "5",
    "₆": "6",
    "₇": "7",
    "₈": "8",
    "₉": "9",
}

COLUMNS_NOT_TO_CHECK = [
    "ARM_DOSE",
    "N_ARM",
    "N_STUDY",
    "ENDPOINT",
    "DVID",
    "ARM_TIME",
    "ARM_TIME_UNIT",
    "DV",
    "DV_UNIT",
]


DV_UNIT_CONSTANTS = [
    "percentage",
    "kg",
    "nmol/l",
    "mg/dl",
    "ng/ml",
    "mmol/mol",
    "mmol/l",
]
DV_STAT_CONSTANTS = [
    "mean",
    "median",
    "geometric mean",
    "mean CFB",
    "LS mean",
    "LS mean CFB",
    "percentage",
]
DV_VAR_STAT_CONSTANTS = ["SEM", "SE", "95% CI", "IQR", "SD"]
